### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by bachue** [docker/fig#873]
When I write fig.yml like this:
```yaml
web:
  build: .
  volumes:
    - .:/var/www/sso
  environment:
    - MOUNTED: true
  ports:
    - "4000:80"
  links:
    - db
```

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.main", line 31, in main
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 21, in sys_dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.command", line 28, in dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 24, in dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.command", line 56, in perform_command
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.main", line 427, in up
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.project", line 174, in up
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 207, in recreate_containers
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 237, in recreate_container
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 176, in create_container
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 370, in _get_container_create_options
TypeError: unhashable type: 'dict'
```

Fig will raise error like this, looks like the root cause is I pass an array in `environment`, if I give a dict, then it works.
My fig version is 1.0.1, docker is 1.3.2

**Comment by marksteve** [comment]
`environment` is a mapping. It should be:

```yaml
environment:
    MOUNTED: true
```

**Comment by bachue** [comment]
@marksteve But in doc it's mentioned

> environment
Add environment variables. You can use either an array or a dictionary.

> Environment variables with only a key are resolved to their values on the machine Fig is running on, which can be helpful for secret or host-specific values.

> ```
environment:
  RACK_ENV: development
  SESSION_SECRET:
environment:
  - RACK_ENV=development
  - SESSION_SECRET
```

**Comment by aanand** [comment]
You've fallen prey to YAML's permissive syntax.

This is an array of strings:

```yaml
environment:
  - MOUNTED=true
```

This is a dictionary:

```yaml
environment:
  MOUNTED: true
```

This is an *array of dictionaries*:

```yaml
environment:
  - MOUNTED: true
```

Sigh.

**Comment by bachue** [comment]
@aanand Yeah, got it. Thanks a lot.

**Comment by jhftrifork** [comment]
I request that this issue be re-opened. The error in the YAML file certainly shouldn't cause an internal error with a stacktrace. Docker-compose should be checking that the YAML file satisfies the expected schema, and providing the user with sensible error messages if it doesn't.

**Comment by aanand** [comment]
This should be handled by the new validation code, which will be out in Compose 1.5.
