### ISSUE TITLE
fig run results in "ValueError: invalid literal for int() with base 16: ''"

### ISSUE THREAD

**Issue by davejohnson** [docker/fig#917]
I'm just following the standard setup for fig + rails (http://www.fig.sh/rails.html) but getting the following error:

```
$ fig run web rails new . --force --database=postgresql --skip-bundle
...
54549384f85a: Download complete
...
b65dcd86995a: Download complete
353cb3772191: Pulling fs layer
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.main", line 31, in main
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 21, in sys_dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.command", line 28, in dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 24, in dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.command", line 56, in perform_command
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.main", line 289, in run
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.project", line 177, in up
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 281, in start_or_create_containers
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.service", line 187, in create_container
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.progress_stream", line 17, in stream_output
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/docker.client", line 289, in _stream_helper
ValueError: invalid literal for int() with base 16: ''
```

There are some issues with docker-py that seem related but not sure that that all fits together.

I'm running the following:

OS X 10.10.1
Docker 1.4.1
Fig 1.0.1

**Comment by aanand** [comment]
Could you paste your `fig.yml` please?

**Comment by davejohnson** [comment]
I upgraded to OS X 10.10.2 last night and everything is working today.

For the record, I was using the ```fig.yml``` right off the fig site for the rails setup (same for the Dockerfile and Gemfile):

```
db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: bundle exec rackup -p 3000
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
```

**Comment by eugeniol** [comment]
Hi @davejohnson,
I have exactly the same issue, did you find what was it?

**Comment by hyhlinux** [comment]
me too, did you find what was it?
