### ISSUE TITLE
File "<string>", line 3, in <module>

### ISSUE THREAD

**Issue by itsNikolay** [docker/fig#930]
```shell
[~/projects/test/docker/myapp]$ docker-compose build                                                                              
bundles uses an image, skipping
db uses an image, skipping
Building web...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 119, in build
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 166, in build
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 479, in build
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 436, in build
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.utils.utils", line 80, in tar
  File "/code/build/docker-compose/out00-PYZ.pyz/tarfile", line 1990, in add
IOError: [Errno 13] Permission denied: './vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.6.2/ports/archives/libxml2-2.9.2.tar.gz'
```
Ubuntu 14.04 x64
[Dockerfile & docker-compose.yml](https://gist.github.com/itsNikolay/b9fa4deac6756303f704)

P.S. but `fig` works well

**Comment by thaJeztah** [comment]
Not sure if it's related, but I noticed you're defining volumes *twice* in your `docker-compose.yml`. first time at [line 15](https://gist.github.com/itsNikolay/b9fa4deac6756303f704#file-docker-compose-yml-L15) and again at [line 21](https://gist.github.com/itsNikolay/b9fa4deac6756303f704#file-docker-compose-yml-L21).

May be worth checking permissions on the directory and files in the project directory. You're mounting the project directory as a volume in the `/myapp` directory inside the container. Docker will use the file permissions *and ownership* of the hosts filesystem when doing that.

Are you using Boot2Docker? And if you do, is the project-directory a VirtualBox shared volume?

**Comment by itsNikolay** [comment]
@thaJeztah thanks for helping, 
I've removed the second volume block. But the issue still happens.
I don't using `boot2docker` becase there's no description about Linux installation, thus I thought it's not required for linux. Fig worked without it. Or is there a diference between docker-compose and fig ?

**Comment by itsNikolay** [comment]
**[SOLVED]**
Short answer: run `rm vendor/bundle -rf` (under the project directory)
Long answer: seems that happens from previous installation of fig, so just remove old local directory located in `/home/your_username/your_myapp/vendor/bundle` and the rerun `docker-compose build`.
Let's going further!

P.S. @thaJeztah you was right with permission issue, thanks one more :+1:

**Comment by thaJeztah** [comment]
@itsNikolay thanks for reporting back and glad to hear you were able to solve your issue. :+1:
